### ISSUE TITLE
Vgg weights and jason file?

### ISSUE THREAD

**Issue by chauhan-utk** [roebius/deeplearning1_keras2#1]
I was trying to run the file but it seems that the vgg.py file downloads vgg weights and imagenet class index in jason format from a web adress 'www.platform.ai' which is not working currently. Can you provide a link to the cached weights and the jason file? Particularly the jason file? I need them to run the file.
Thanks in advance.

**Comment by roebius** [comment]
The original download source was moved a few weeks ago to *files.fast.ai* but the *model* subdir there does not appear on the web page. You can manually download both files file from a terminal window using the commands:
*wget files.fast.ai/models/vgg16.h5*
*wget files.fast.ai/models/imagenet_class_index.json*

If you are using Keras' default settings, both files should be placed into the *~/.keras/models* dir. Let me know if you have any issues

**Comment by roebius** [comment]
Another solution could be to edit vgg16.py and replace the original address for download with the new one under *def __init__(self):*:
*self.FILE_PATH = 'http://files.fast.ai/models/'*

In this case no need to manually download the files, since they will be downloaded the first time the *lesson1* notebook will be executed.

**Comment by chauhan-utk** [comment]
I actually looked into my cache directory and found another weight file downloaded for vgg16 and the imagenet class index jason. Thanks for the update on change of model download location.

**Comment by roebius** [comment]
I have updated the repo so that *vgg16.py, vgg16bn.py, resnet50.py* now use the current actual  download path.
