### ISSUE TITLE
Suggestion: Set Keras parameters programmatically instead of via JSON

### ISSUE THREAD

**Issue by pisymbol** [roebius/deeplearning1_keras2#10]
Instead of having users copy over a JSON config file to run a notebook, why not add the following to every lesson:

from keras import backend as K
K.set_image_data_format('channels_last')
K.set_image_dim_ordering('th')

This works for me without any issue while allowing me to preserve my existing Keras config. I'm using a Tensorflow backend on an NVidia GPU.

**Comment by roebius** [comment]
Using the Keras JSON config file will help change the backend for _all_ the notebooks without the need to edit each one, so I think in general it's more convenient.
Thanks anyway for your suggestion, which could be particularly useful for changing the backend individually for selected notebooks.

As a side note: if I am not wrong, `set_image_dim_ordering` is obsolete with Keras 2.

**Comment by pisymbol** [comment]
Yes, but it overrides existing work spaces, which means if folks already have Keras setups (like I do) I have to back up my existing config and restore it after executing these notebooks. It's fine if everyone is going to use AWS EC2 but it's not so great on a local machine that maybe running several notebooks for a myriad array of classes/MOOC etc.

Having these two lines across different notebooks is no different than the duplicate import statements and as you said, also allows students to change the backend (e.g. 'cntk') with very little pain.

**Comment by roebius** [comment]
Your point is a good one, however I am not sure how many Fastai students have already their personal Keras setups vs how many are just complete beginners. I could put your suggestion in a note and leave up to the users the choice.
My goal was also to not change the original Fastai material unchanged as much as possible.
