### ISSUE TITLE
'DirectoryIterator' object has no attribute 'num_class'

### ISSUE THREAD

**Issue by arifoyong** [roebius/deeplearning1_keras2#11]
Hi Robi,  

Thanks for sharing this great work. I tried the copy for lesson01. 

I have the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-e637d623c59d> in <module>()
----> 1 vgg.finetune(batches)
      2 vgg.fit(batches, val_batches, batch_size, nb_epoch=1)
      3 

C:\Users\Wen\Documents\Python file_Arif\fastai\vgg16.py in finetune(self, batches)
     95 
     96     def finetune(self, batches):
---> 97         self.ft(batches.num_class)  # Keras2
     98         classes = list(iter(batches.class_indices))
     99         for c in batches.class_indices:

AttributeError: 'DirectoryIterator' object has no attribute 'num_class'
```

Do you know what is the problem?

As a note:
- I've updated the .keras/keras.json file as suggested (I'm using theano btw)
- I'm using Keras 2.1.2

**Comment by arifoyong** [comment]
Hi, 
Apparently it worked after I change it to the following:
`self.ft(batches.num_classes) `

Maybe there is an update in Keras 2.1.2.
I've yet to check it though.

**Comment by roebius** [comment]
Hi @arifoyong ,
thank you for checking the notebooks.
You are correct: have a look at the thread for [this pull request](https://github.com/roebius/deeplearning_keras2/pull/9).
At the moment the notebooks are still the ones tested with Keras 2.0.6. I plan to release an update in January.

**Comment by hilakibe** [comment]
I am facing the same problem
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-373624847ddc> in <module>
----> 1 scores=model.evaluate(validation_generator,  verbose=0)

~\Anaconda3\envs\other\lib\site-packages\keras\engine\training.py in evaluate(self, x, y, batch_size, verbose, sample_weight, steps)
   1100             x, y,
   1101             sample_weight=sample_weight,
-> 1102             batch_size=batch_size)
   1103         # Prepare inputs, delegate logic to `test_loop`.
   1104         if self._uses_dynamic_learning_phase():

~\Anaconda3\envs\other\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749             feed_input_shapes,
    750             check_batch_axis=False,  # Don't enforce the batch size.
--> 751             exception_prefix='input')
    752 
    753         if y is not None:

~\Anaconda3\envs\other\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
     90         data = data.values if data.__class__.__name__ == 'DataFrame' else data
     91         data = [data]
---> 92     data = [standardize_single_array(x) for x in data]
     93 
     94     if len(data) != len(names):

~\Anaconda3\envs\other\lib\site-packages\keras\engine\training_utils.py in <listcomp>(.0)
     90         data = data.values if data.__class__.__name__ == 'DataFrame' else data
     91         data = [data]
---> 92     data = [standardize_single_array(x) for x in data]
     93 
     94     if len(data) != len(names):

~\Anaconda3\envs\other\lib\site-packages\keras\engine\training_utils.py in standardize_single_array(x)
     25                 'Got tensor with shape: %s' % str(shape))
     26         return x
---> 27     elif x.ndim == 1:
     28         x = np.expand_dims(x, 1)
     29     return x

AttributeError: 'DirectoryIterator' object has no attribute 'ndim'
