### ISSUE TITLE
Can't pip install pygpu on Python 3.5 / Ubuntu 16

### ISSUE THREAD

**Issue by bluelight773** [roebius/deeplearning1_keras2#3]
When I try to run the following to ensure I have the necessary packages for Part 1 with Keras 2 and Python 3.5 on Ubuntu 16.04:
`pip install -r requirements_part1_ubuntu.txt `, I always get an error regarding the install of pygpu.

I can reproduce this error if I simply type either of the following as well:
`pip install pygpu`
`pip install pygpu==0.6.4`

>   Could not find a version that satisfies the requirement pygpu (from versions: )
> No matching distribution found for pygpu

Now I did find a way around this by following the instruction here: http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install  However, it would definitely way more convenient if one could install pygpu via pip instead of the much longer/verbose process at that link.

Any idea how one can get pip to install pygpu (in the context of Python 3.5 / Ubuntu 16)?  Anything I may be missing?

Thanks

**Comment by roebius** [comment]
Actually I did not find a way myself to install gpuarray/pygpu by using pip, so I created an install bash script: [install_gpuarray_pygpu.sh.zip](https://github.com/roebius/deeplearning_keras2/files/1332072/install_gpuarray_pygpu.sh.zip).
Launching the script after activating the target Python 3 virtualenv, the script creates an auxiliary folder for cloning the source repo and running the makefile, and installs gpuarray/pygpu for the "user library" (as described at http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install). I have not tried the "system library" installation.  
Before running the script it is important to check the install requirements listed at the same link.  
Also, you might want to edit the script to better suit your install environment, and maybe run it in a test Python 3 virtualenv.

If you use the script let me know if it works for you.
