### ISSUE TITLE
ValueError: ('The specified size contains a dimension with value <= 0', (4096, 0))

### ISSUE THREAD

**Issue by taewookim** [roebius/deeplearning1_keras2#6]
ubuntu 16.04 LTS, no GPU w/ python 3.5.2 
all packages were installed recently (as of 10/7/2017)
Made sure theano backend is setup

in Lesson1.ipynb, i am getting this error.

Any deas?

```
vgg = Vgg16()
# Grab a few images at a time for training and validation.
# NB: They must be in subdirectories named based on their category
batches = vgg.get_batches(path+'train', batch_size=batch_size)
val_batches = vgg.get_batches(path+'valid', batch_size=batch_size*2)
vgg.finetune(batches)
vgg.fit(batches, val_batches, batch_size, nb_epoch=1)

```

Found 0 images belonging to 0 classes.
Found 0 images belonging to 0 classes.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-fe7340b1a18b> in <module>()
      4 batches = vgg.get_batches(path+'train', batch_size=batch_size)
      5 val_batches = vgg.get_batches(path+'valid', batch_size=batch_size*2)
----> 6 vgg.finetune(batches)
      7 vgg.fit(batches, val_batches, batch_size, nb_epoch=1)

/mnt/hgfs/T/security/fast.ai/courses/deeplearning1/nbs/vgg16.py in finetune(self, batches)
     95 
     96     def finetune(self, batches):
---> 97         self.ft(batches.num_class)  # Keras2
     98         classes = list(iter(batches.class_indices))
     99         for c in batches.class_indices:

/mnt/hgfs/T/security/fast.ai/courses/deeplearning1/nbs/vgg16.py in ft(self, num)
     91         model.pop()
     92         for layer in model.layers: layer.trainable=False
---> 93         model.add(Dense(num, activation='softmax'))
     94         self.compile()
     95 

/usr/local/lib/python3.5/dist-packages/keras/models.py in add(self, layer)
    453                           output_shapes=[self.outputs[0]._keras_shape])
    454         else:
--> 455             output_tensor = layer(self.outputs[0])
    456             if isinstance(output_tensor, list):
    457                 raise TypeError('All layers in a Sequential model '

/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    526                                          '`layer.build(batch_input_shape)`')
    527                 if len(input_shapes) == 1:
--> 528                     self.build(input_shapes[0])
    529                 else:
    530                     self.build(input_shapes)

/usr/local/lib/python3.5/dist-packages/keras/layers/core.py in build(self, input_shape)
    825                                       name='kernel',
    826                                       regularizer=self.kernel_regularizer,
--> 827                                       constraint=self.kernel_constraint)
    828         if self.use_bias:
    829             self.bias = self.add_weight((self.units,),

/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in add_weight(self, shape, initializer, name, trainable, regularizer, constraint)
    362         """
    363         initializer = initializers.get(initializer)
--> 364         weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
    365         if regularizer is not None:
    366             self.add_loss(regularizer(weight))

/usr/local/lib/python3.5/dist-packages/keras/initializers.py in __call__(self, shape, dtype)
    203             limit = np.sqrt(3. * scale)
    204             return K.random_uniform(shape, -limit, limit,
--> 205                                     dtype=dtype, seed=self.seed)
    206 
    207     def get_config(self):

/usr/local/lib/python3.5/dist-packages/keras/backend/theano_backend.py in random_uniform(shape, minval, maxval, dtype, seed)
   1967         seed = np.random.randint(1, 10e6)
   1968     rng = RandomStreams(seed=seed)
-> 1969     return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
   1970 
   1971 

/usr/local/lib/python3.5/dist-packages/theano/sandbox/rng_mrg.py in uniform(self, size, low, high, ndim, dtype, nstreams)
   1342                 raise ValueError(
   1343                     "The specified size contains a dimension with value <= 0",
-> 1344                     size)
   1345 
   1346         else:

ValueError: ('The specified size contains a dimension with value <= 0', (4096, 0))

**Comment by roebius** [comment]
Referring to the message 
> Found 0 images belonging to 0 classes.

it could be that you are not using the full dataset but just a sample, and that some class in your  sample does not have any file associated with it. This could generate the rest of the error message.

**Comment by roebius** [comment]
(closed by mistake, now reopened)

**Comment by taewookim** [comment]
Oh yes.. u;re right. I was pointing to the sample, instead of the actual  full data directory.

But now i'm getting this error though:

> Found 23000 images belonging to 2 classes.
> Found 0 images belonging to 0 classes.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-38-fe7340b1a18b> in <module>()
>       5 val_batches = vgg.get_batches(path+'valid', batch_size=batch_size*2)
>       6 vgg.finetune(batches)
> ----> 7 vgg.fit(batches, val_batches, batch_size, nb_epoch=1)
> 
> /mnt/hgfs/T/security/fast.ai/courses/deeplearning1/nbs/vgg16.py in fit(self, batches, val_batches, batch_size, nb_epoch)
>     116     def fit(self, batches, val_batches, batch_size, nb_epoch=1):
>     117         self.model.fit_generator(batches, steps_per_epoch=int(np.ceil(batches.samples/batch_size)), epochs=nb_epoch,
> --> 118                 validation_data=val_batches, validation_steps=int(np.ceil(val_batches.samples/batch_size)))
>     119 
>     120 
> 
> /usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
>      86                 warnings.warn('Update your `' + object_name +
>      87                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
> ---> 88             return func(*args, **kwargs)
>      89         wrapper._legacy_support_signature = inspect.getargspec(func)
>      90         return wrapper
> 
> /usr/local/lib/python3.5/dist-packages/keras/models.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_q_size, workers, pickle_safe, initial_epoch)
>    1095                                         workers=workers,
>    1096                                         pickle_safe=pickle_safe,
> -> 1097                                         initial_epoch=initial_epoch)
>    1098 
>    1099     @interfaces.legacy_generator_methods_support
> 
> /usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
>      86                 warnings.warn('Update your `' + object_name +
>      87                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
> ---> 88             return func(*args, **kwargs)
>      89         wrapper._legacy_support_signature = inspect.getargspec(func)
>      90         return wrapper
> 
> /usr/local/lib/python3.5/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_q_size, workers, pickle_safe, initial_epoch)
>    1781                    hasattr(validation_data, '__next__'))
>    1782         if val_gen and not validation_steps:
> -> 1783             raise ValueError('When using a generator for validation data, '
>    1784                              'you must specify a value for '
>    1785                              '`validation_steps`.')
> 
> ValueError: When using a generator for validation data, you must specify a value for `validation_steps`.
>

**Comment by roebius** [comment]
So it seems that you solved the issue for the training batches, while for the validation batches it is still there: double check that also in your valid directories you have something for each class. 
You should have some file for each class in both your train and your valid dirs.

**Comment by taewookim** [comment]
jeremy's  lesson on setting up the directory was confusing to me.

can you post the directory structure ?

is it something like

dogsandcats
dogsandcats/train
dogsandcats/train/cat
dogsandcats/train/dog
dogsandcats/test

?

**Comment by roebius** [comment]
dogscats (main dir)
dogscats/train/cats (train images)
dogscats/train/dogs (train images)
dogscats/valid/cats (validation images)
dogscats/valid/dogs (validation images)

dogscats/test/unknown (in order to be used by Keras, the test images go to a dummy class directory under the test subdir)

If you want to use a "sample" dir, then under the "sample" subfolder you need to put again all the dirs listed above. Every final subfolder needs to contain at least 1 image file.

**Comment by vteodorescu** [comment]
Whoa, I did not know about the "/test/unknown" trick! Thank you, @roebius!

**Comment by taewookim** [comment]
Yea, you da man @roebius . Thanks!
